### ISSUE TITLE
Problem with different then konami :/

### ISSUE THREAD

**Issue by vAhyThe** [d-kalh/vue-konami#3]
whe i try diferent code then conami something like `force`= `70-79-82-67-69` dont work

**Comment by d-kalh** [comment]
Seems weird.
Could you paste a code example so I can check ?

**Comment by vAhyThe** [comment]
`<div v-konami="easterEgg" />`
``` data() {
      return {
        opts: {
          timeout: 3000,
          chain: '70-79-82-67-69',
        },
      }
    },
```
```
      easterEgg() {
        console.log('I\'m a totally useful easter egg.')
      },
```

**Comment by d-kalh** [comment]
Ok, in order to use the custom opts property, you have to set it on the v-konami directive.
`<div v-konami:opts.custom="easterEgg"></div>`
This should work, could you confirm ? :)

**Comment by vAhyThe** [comment]
@d-kalh it works perefectly thx :)
